// ============================================================
// BKNR ERP — Menu Data (mirrors menu.html sidebarMenuData)
// ============================================================

export const MENU_DATA = [
  {
    id: 'dashboards',
    title: 'Dashboards',
    icon: 'pie-chart',
    color: '#3b82f6',
    bgColor: 'rgba(59, 130, 246, 0.12)',
    modules: [
      { id: 'processing_dashboard', label: 'Processing Dashboard', icon: 'bar-chart-2', route: '/dashboard/processing_dashboard', badge: 'LIVE' },
      { id: 'inventory_dashboard', label: 'Inventory Dashboard', icon: 'package', route: '/dashboard/inventory_dashboard', badge: 'LIVE' },
      { id: 'hr_command_center', label: 'HR & Staff', icon: 'users', route: '/dashboard/hr_command_center', badge: 'LIVE' },
      { id: 'costing_dashboard', label: 'Costing & Finance', icon: 'dollar-sign', route: '/dashboard/costing_dashboard', badge: 'LIVE' },
      { id: 'finance_dashboard', label: 'Finance Dashboard', icon: 'credit-card', route: '/dashboard/finance_dashboard', badge: 'LIVE' },
    ],
  },
  {
    id: 'operations',
    title: 'Operations',
    icon: 'settings',
    color: '#ea580c',
    bgColor: 'rgba(234, 88, 12, 0.12)',
    modules: [
      // Processing subgroup
      { id: 'gate_entry', label: 'Gate Entry', icon: 'log-in', route: '/processing/gate_entry', badge: 'Ops-1', subgroup: 'Processing' },
      { id: 'raw_material_purchasing', label: 'RM Purchasing', icon: 'truck', route: '/processing/raw_material_purchasing', badge: 'Ops-2', subgroup: 'Processing' },
      { id: 'de_heading', label: 'De-Heading', icon: 'scissors', route: '/processing/de_heading', badge: 'WIP', subgroup: 'Processing' },
      { id: 'grading', label: 'Grading', icon: 'filter', route: '/processing/grading', badge: 'WIP', subgroup: 'Processing' },
      { id: 'peeling', label: 'Peeling', icon: 'layers', route: '/processing/peeling', badge: 'WIP', subgroup: 'Processing' },
      { id: 'soaking', label: 'Soaking', icon: 'droplet', route: '/processing/soaking', badge: 'WIP', subgroup: 'Processing' },
      { id: 'production', label: 'Production', icon: 'cpu', route: '/processing/production', badge: 'WIP', subgroup: 'Processing' },
      // Inventory subgroup
      { id: 'stock_entry', label: 'Stock Entry', icon: 'archive', route: '/inventory/stock_entry', badge: 'Stock', subgroup: 'Inventory' },
      { id: 'pending_orders', label: 'Pending Orders', icon: 'clock', route: '/inventory/pending_orders', badge: 'Orders', subgroup: 'Inventory' },
      { id: 'cold_storage_holding', label: 'Cold Storage Holding', icon: 'thermometer', route: '/inventory/cold_storage_holding', badge: 'Cold', subgroup: 'Inventory' },
      { id: 'general_store_entry', label: 'General Store Entry', icon: 'shopping-bag', route: '/general_stock/entry', badge: 'Store', subgroup: 'Inventory' },
      // Export Documents subgroup
      { id: 'export_shipment', label: 'Export Shipments', icon: 'anchor', route: '/export_documents/export_shipment/entry', badge: 'ExpOp', subgroup: 'Export Documents' },
      { id: 'commercial_invoice', label: 'Commercial Invoices', icon: 'file-text', route: '/export_documents/commercial_invoice/entry', badge: 'ExpOp', subgroup: 'Export Documents' },
      { id: 'packing_list', label: 'Packing Lists', icon: 'list', route: '/export_documents/packing_list/entry', badge: 'ExpOp', subgroup: 'Export Documents' },
      { id: 'container_stuffing', label: 'Container Stuffing', icon: 'box', route: '/export_documents/container_stuffing/entry', badge: 'ExpOp', subgroup: 'Export Documents' },
      { id: 'shipping_bill', label: 'Shipping Bills', icon: 'clipboard', route: '/export_documents/shipping_bill/entry', badge: 'ExpOp', subgroup: 'Export Documents' },
      { id: 'bill_of_lading', label: 'Bills of Lading', icon: 'file', route: '/export_documents/bill_of_lading/entry', badge: 'ExpOp', subgroup: 'Export Documents' },
      { id: 'health_certificate', label: 'Health Certificates', icon: 'shield', route: '/export_documents/health_certificate/entry', badge: 'ExpOp', subgroup: 'Export Documents' },
    ],
  },
  {
    id: 'finance',
    title: 'Finance',
    icon: 'dollar-sign',
    color: '#10b981',
    bgColor: 'rgba(16, 185, 129, 0.12)',
    modules: [
      // Commercial Bills subgroup
      { id: 'electricity_bills', label: 'Electricity Bills', icon: 'zap', route: '/api/electricity/entry', badge: 'Exp', subgroup: 'Commercial Bills' },
      { id: 'diesel_bills', label: 'Diesel Consumption', icon: 'droplet', route: '/api/diesel/entry', badge: 'Exp', subgroup: 'Commercial Bills' },
      { id: 'packaging_bills', label: 'Purchase & Packaging', icon: 'package', route: '/api/purchase/entry', badge: 'Exp', subgroup: 'Commercial Bills' },
      { id: 'logistics_bills', label: 'Logistics & Freight', icon: 'truck', route: '/api/container/entry', badge: 'Exp', subgroup: 'Commercial Bills' },
      { id: 'qa_testing', label: 'QA Testing Charges', icon: 'check-circle', route: '/api/qa/entry', badge: 'Exp', subgroup: 'Commercial Bills' },
      { id: 'other_expenses', label: 'Other Expenses', icon: 'credit-card', route: '/api/expenses/entry', badge: 'Misc', subgroup: 'Commercial Bills' },
      // Accounts & Ledgers subgroup
      { id: 'ledger_master', label: 'Ledger Master', icon: 'book-open', route: '/finance_accounts/ledger_master/entry', badge: 'Acc', subgroup: 'Accounts & Ledgers' },
      { id: 'journal_entry', label: 'Journal Entries', icon: 'book', route: '/finance_accounts/journal_entry/entry', badge: 'Acc', subgroup: 'Accounts & Ledgers' },
      // Cash & Banking subgroup
      { id: 'bank_transaction', label: 'Bank Transactions', icon: 'layers', route: '/finance_accounts/bank_transaction/entry', badge: 'Bank', subgroup: 'Cash & Banking' },
      { id: 'payment_receipt', label: 'Remittance & Receipts', icon: 'dollar-sign', route: '/finance_accounts/payment_receipt/entry', badge: 'Bank', subgroup: 'Cash & Banking' },
      // Payables & Receivables subgroup
      { id: 'customer_receivable', label: 'Customer Receivables', icon: 'trending-up', route: '/finance_accounts/customer_receivable/entry', badge: 'Fin', subgroup: 'Payables & Receivables' },
      { id: 'vendor_payment', label: 'Vendor Payments', icon: 'arrow-up-right', route: '/finance_accounts/vendor_payment/entry', badge: 'Fin', subgroup: 'Payables & Receivables' },
      { id: 'expense_voucher', label: 'Expense Vouchers', icon: 'file-minus', route: '/finance_accounts/expense_voucher/entry', badge: 'Fin', subgroup: 'Payables & Receivables' },
    ],
  },
  {
    id: 'reports',
    title: 'Reports',
    icon: 'file-text',
    color: '#8b5cf6',
    bgColor: 'rgba(139, 92, 246, 0.12)',
    modules: [
      // Processing Reports subgroup
      { id: 'gate_entry_report', label: 'Gate Entry Report', icon: 'file', route: '/reports/gate_entry', badge: 'Logs', subgroup: 'Processing Reports' },
      { id: 'rmp_report', label: 'RM Purchase Report', icon: 'file', route: '/reports/raw_material_purchasing', badge: 'Data', subgroup: 'Processing Reports' },
      { id: 'de_heading_report', label: 'De-Heading Report', icon: 'file', route: '/reports/de_heading', badge: 'Data', subgroup: 'Processing Reports' },
      { id: 'grading_report', label: 'Grading Report', icon: 'file', route: '/reports/grading_report', badge: 'Data', subgroup: 'Processing Reports' },
      { id: 'peeling_report', label: 'Peeling Report', icon: 'file', route: '/reports/peeling_report', badge: 'Data', subgroup: 'Processing Reports' },
      { id: 'soaking_report', label: 'Soaking Report', icon: 'file', route: '/reports/soaking_report', badge: 'Data', subgroup: 'Processing Reports' },
      { id: 'production_report', label: 'Production Report', icon: 'file', route: '/reports/production_report', badge: 'Data', subgroup: 'Processing Reports' },
      { id: 'reprocess_report', label: 'Re-Process Report', icon: 'refresh-cw', route: '/reports/re-process', badge: 'Logs', subgroup: 'Processing Reports' },
      // Inventory Reports subgroup
      { id: 'floor_balance_report', label: 'Floor Balance Report', icon: 'bar-chart', route: '/reports/floor_balance_report', badge: 'Stock', subgroup: 'Inventory Reports' },
      { id: 'inventory_report', label: 'Stock Status Report', icon: 'box', route: '/inventory/stock_report', badge: 'Inv', subgroup: 'Inventory Reports' },
      { id: 'pending_orders_report', label: 'Pending Orders Report', icon: 'clock', route: '/reports/pending_orders_report', badge: 'Hold', subgroup: 'Inventory Reports' },
      { id: 'sales_report', label: 'Sales Report', icon: 'trending-up', route: '/inventory/sales_report', badge: 'Out', subgroup: 'Inventory Reports' },
      { id: 'gs_report', label: 'General Store Report', icon: 'shopping-bag', route: '/general_stock/report', badge: 'Store', subgroup: 'Inventory Reports' },
      { id: 'cold_storage_holding_report', label: 'Cold Storage Report', icon: 'thermometer', route: '/inventory/cold_storage_holding_report', badge: 'Cold', subgroup: 'Inventory Reports' },
      // Costing Reports subgroup
      { id: 'storage_cost_report', label: 'Storage & Cost Report', icon: 'dollar-sign', route: '/reports/storage_cost_report', badge: 'Val', subgroup: 'Costing Reports' },
      { id: 'floor_balance_value', label: 'Floor Balance Value', icon: 'layers', route: '/summary/floor_balance_value', badge: 'Val', subgroup: 'Costing Reports' },
      { id: 'inventory_costing', label: 'Inventory Costing', icon: 'percent', route: '/summary/inventory_costing', badge: 'Fin', subgroup: 'Costing Reports' },
      { id: 'periodic_summary', label: 'Periodic Summary', icon: 'calendar', route: '/summary/periodic-report', badge: 'Time', subgroup: 'Costing Reports' },
      { id: 'batch_summary', label: 'Batch Summary', icon: 'list', route: '/summary/processing', badge: 'Run', subgroup: 'Costing Reports' },
    ],
  },
  {
    id: 'hrms',
    title: 'HRMS',
    icon: 'users',
    color: '#ec4899',
    bgColor: 'rgba(236, 72, 153, 0.12)',
    modules: [
      { id: 'employee_registration', label: 'Staff Registration', icon: 'user-plus', route: '/attendance/employee/register', badge: 'HR' },
      { id: 'employee_increment', label: 'Increment Details', icon: 'trending-up', route: '/attendance/employee-increment', badge: 'HR' },
      { id: 'daily_attendance', label: 'Daily Attendance', icon: 'check-square', route: '/attendance/daily', badge: 'HR' },
      { id: 'salary_report', label: 'Monthly Salary Sheet', icon: 'dollar-sign', route: '/attendance/salary/monthly-sheet', badge: 'HR' },
      { id: 'tax_master', label: 'Payroll Master', icon: 'shield', route: '/attendance/tax-master', badge: 'HR' },
      { id: 'salary_advance', label: 'Salary Advance', icon: 'arrow-up-circle', route: '/attendance/salary-advance', badge: 'HR' },
    ],
  },
  {
    id: 'masters',
    title: 'Masters',
    icon: 'database',
    color: '#64748b',
    bgColor: 'rgba(100, 116, 139, 0.12)',
    modules: [
      // Business Masters
      { id: 'buyers', label: 'Buyers', icon: 'user', route: '/criteria/buyers', badge: 'Mstr', subgroup: 'Business Masters' },
      { id: 'buyer_agents', label: 'Buyer Agents', icon: 'user', route: '/criteria/buyer_agents', badge: 'Mstr', subgroup: 'Business Masters' },
      { id: 'suppliers', label: 'Suppliers', icon: 'user', route: '/criteria/suppliers', badge: 'Mstr', subgroup: 'Business Masters' },
      { id: 'vendors', label: 'Vendors', icon: 'user', route: '/criteria/vendors', badge: 'Mstr', subgroup: 'Business Masters' },
      { id: 'countries', label: 'Countries', icon: 'globe', route: '/criteria/countries', badge: 'Mstr', subgroup: 'Business Masters' },
      { id: 'brands', label: 'Brands', icon: 'tag', route: '/criteria/brands', badge: 'Mstr', subgroup: 'Business Masters' },
      { id: 'purchasing_locations', label: 'Purchasing Locations', icon: 'map-pin', route: '/criteria/purchasing_locations', badge: 'Mstr', subgroup: 'Business Masters' },
      // Production Masters
      { id: 'species', label: 'Species', icon: 'layers', route: '/criteria/species', badge: 'Prod', subgroup: 'Production Masters' },
      { id: 'varieties', label: 'Varieties', icon: 'layers', route: '/criteria/varieties', badge: 'Prod', subgroup: 'Production Masters' },
      { id: 'grades', label: 'Grades', icon: 'star', route: '/criteria/grades', badge: 'Prod', subgroup: 'Production Masters' },
      { id: 'freezers', label: 'Freezers', icon: 'thermometer', route: '/criteria/freezers', badge: 'Prod', subgroup: 'Production Masters' },
      { id: 'glazes', label: 'Glazes', icon: 'droplet', route: '/criteria/glazes', badge: 'Prod', subgroup: 'Production Masters' },
      { id: 'packing_styles', label: 'Packing Styles', icon: 'box', route: '/criteria/packing_styles', badge: 'Prod', subgroup: 'Production Masters' },
      { id: 'contractors', label: 'Contractors', icon: 'briefcase', route: '/criteria/contractors', badge: 'Prod', subgroup: 'Production Masters' },
      { id: 'peeling_at', label: 'Peeling At', icon: 'map-pin', route: '/criteria/peeling_at', badge: 'Prod', subgroup: 'Production Masters' },
      { id: 'peeling_rates', label: 'Peeling Rates', icon: 'percent', route: '/criteria/peeling_rates', badge: 'Prod', subgroup: 'Production Masters' },
      { id: 'production_at', label: 'Production At', icon: 'home', route: '/criteria/production_at', badge: 'Prod', subgroup: 'Production Masters' },
      { id: 'production_for', label: 'Production For', icon: 'briefcase', route: '/criteria/production_for', badge: 'Prod', subgroup: 'Production Masters' },
      { id: 'production_types', label: 'Production Types', icon: 'list', route: '/criteria/production_types', badge: 'Prod', subgroup: 'Production Masters' },
      { id: 'chemicals', label: 'Chemicals', icon: 'activity', route: '/criteria/chemicals', badge: 'Prod', subgroup: 'Production Masters' },
      { id: 'purposes', label: 'Purposes', icon: 'target', route: '/criteria/purposes', badge: 'Prod', subgroup: 'Production Masters' },
      { id: 'grade_to_hoso', label: 'Grade to HOSO', icon: 'arrow-right', route: '/criteria/grade_to_hoso', badge: 'Prod', subgroup: 'Production Masters' },
      { id: 'hoso_hlso', label: 'HOSO & HLSO', icon: 'repeat', route: '/criteria/hoso_hlso', badge: 'Prod', subgroup: 'Production Masters' },
      // Inventory Masters
      { id: 'cold_storage_master', label: 'Cold Storage Master', icon: 'thermometer', route: '/inventory/cold_storage', badge: 'InvM', subgroup: 'Inventory Masters' },
      { id: 'coldstore_locations', label: 'Coldstore Locations', icon: 'map', route: '/criteria/coldstore_locations', badge: 'InvM', subgroup: 'Inventory Masters' },
      { id: 'vehicle_numbers', label: 'Vehicle Numbers', icon: 'truck', route: '/criteria/vehicle_numbers', badge: 'InvM', subgroup: 'Inventory Masters' },
      // Finance Masters
      { id: 'hsn_codes', label: 'HSN Codes', icon: 'hash', route: '/criteria/hsn_codes', badge: 'FinM', subgroup: 'Finance Masters' },
    ],
  },
  {
    id: 'admin',
    title: 'Admin & Help',
    icon: 'shield',
    color: '#94a3b8',
    bgColor: 'rgba(148, 163, 184, 0.12)',
    modules: [
      { id: 'add_user', label: 'User Configuration', icon: 'user-check', route: '/admin/add_user', badge: 'Admin', subgroup: 'Admin Console' },
      { id: 'shifts', label: 'Shifts', icon: 'clock', route: '/attendance/shifts', badge: 'Admin', subgroup: 'Admin Console' },
      { id: 'data_management', label: 'Data Management', icon: 'database', route: '/data-management', badge: 'Admin', subgroup: 'Admin Console' },
      { id: 'raise_ticket', label: 'My Complaints', icon: 'message-square', route: '/support/my_tickets', badge: 'Help', subgroup: 'Help & Support' },
      { id: 'admin_helpdesk', label: 'User Complaints', icon: 'headphones', route: '/admin/all_tickets', badge: 'Live', subgroup: 'Super Admin Panel' },
      { id: 'manage_support', label: 'Add Support Team', icon: 'user-plus', route: '/admin/support_team', badge: 'Config', subgroup: 'Super Admin Panel' },
      { id: 'user_activity', label: 'User Activity Logs', icon: 'activity', route: '/admin/activities', badge: 'Logs', subgroup: 'Super Admin Panel' },
    ],
  },
];
